[package]
name = "url_shortner"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
diesel = { version = "2.2.0", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
dotenv = "0.15.0"
random-string = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"